# Generated by Django 4.1.7 on 2023-03-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True)),
                ('failed', models.BooleanField(null=True)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
